server:
  port: 8082

spring:
  application:
    name: project-service

eureka:
  client:
    registryFetchIntervalSeconds: 5
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.openfeign: DEBUG

resilience4j:
  circuitbreaker:
    instances:
      userService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
  retry:
    instances:
      userServiceRetry:
        maxAttempts: 3
        waitDuration: 2s


timelimiter:
  instances:
    userServiceTimeout:
      timeoutDuration: 3s

  bulkhead:
    instances:
      userServiceBulkhead:
        maxConcurrentCalls: 5 #Only 5 concurrent requests are dedicated to userservice
        maxWaitDuration: 0