server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/nayeemshaik3112/project-management-config-repo
          clone-on-start: true

config-server:
  build: ./config-server
  container_name: config-server
  ports:
    - "8888:8888"

management:
  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans